export const uiCopy = {
  en: {
    brand: "Dholera Infrastructure Intelligence",
    nav_home: "Home",
    nav_feed: "Growth Tracker",
    nav_maps: "Project Maps",
    nav_growth: "Future Growth",
    nav_contact: "Contact",
    cta_whatsapp: "WhatsApp Now",
    cta_site_visit: "Request Site Visit",
    cta_brief: "Download Project Brief",
    cta_price_sheet: "Request Price Sheet",
    cta_map_request: "Request Map Pack",
    cta_consultation: "Book Consultation",
    latest_activity: "Infrastructure Activity",
    feed_intro: "Infrastructure Intelligence Monitor",
    maps_heading: "Maps & Connectivity",
    growth_heading: "Why This Area Is Growing",
    contact_heading: "Start an investment conversation",
    lead_name: "Full name",
    lead_phone: "Phone number",
    lead_email: "Email address",
    lead_message: "What would you like to know?",
    lead_visit_date: "Preferred site visit date",
    lead_submit: "Send inquiry",
    admin_login: "Admin Login",
    admin_updates: "Updates",
    admin_leads: "Leads",
    admin_dashboard: "Overview",
    featured: "Featured",
    related_updates: "Related updates",
    back_to_feed: "Back to tracker",
    read_more: "Read update",
    filters_search: "Search activity",
    filters_category: "Category",
    filters_all: "All activity",
    no_updates: "No activity found for the current filters.",
    lead_success: "Inquiry received. Our team will reach out shortly.",
    lead_error: "We could not submit your inquiry right now.",
    admin_status: "Status",
    admin_save: "Save update",
    admin_delete: "Delete",
    admin_edit: "Edit",
    admin_logout: "Logout",
  },
  hi: {
    brand: "धोलेरा इन्फ्रास्ट्रक्चर इंटेलिजेंस",
    nav_home: "होम",
    nav_feed: "ग्रोथ ट्रैकर",
    nav_maps: "प्रोजेक्ट मैप्स",
    nav_growth: "भविष्य की वृद्धि",
    nav_contact: "संपर्क",
    cta_whatsapp: "व्हाट्सऐप करें",
    cta_site_visit: "साइट विजिट अनुरोध",
    cta_brief: "प्रोजेक्ट ब्रीफ डाउनलोड करें",
    cta_price_sheet: "प्राइस शीट मांगें",
    cta_map_request: "मैप पैक मांगें",
    cta_consultation: "कंसल्टेशन बुक करें",
    latest_activity: "इन्फ्रास्ट्रक्चर गतिविधि",
    feed_intro: "इन्फ्रास्ट्रक्चर इंटेलिजेंस मॉनिटर",
    maps_heading: "मैप्स और कनेक्टिविटी",
    growth_heading: "यह क्षेत्र क्यों बढ़ रहा है",
    contact_heading: "निवेश वार्ता शुरू करें",
    lead_name: "पूरा नाम",
    lead_phone: "फोन नंबर",
    lead_email: "ईमेल पता",
    lead_message: "आप क्या जानना चाहते हैं?",
    lead_visit_date: "पसंदीदा साइट विजिट तिथि",
    lead_submit: "पूछताछ भेजें",
    admin_login: "एडमिन लॉगिन",
    admin_updates: "अपडेट्स",
    admin_leads: "लीड्स",
    admin_dashboard: "ओवरव्यू",
    featured: "फीचर्ड",
    related_updates: "संबंधित अपडेट्स",
    back_to_feed: "ट्रैकर पर वापस जाएँ",
    read_more: "अपडेट पढ़ें",
    filters_search: "गतिविधि खोजें",
    filters_category: "श्रेणी",
    filters_all: "सभी गतिविधियाँ",
    no_updates: "वर्तमान फिल्टर के लिए कोई गतिविधि नहीं मिली।",
    lead_success: "पूछताछ प्राप्त हुई। हमारी टीम शीघ्र संपर्क करेगी।",
    lead_error: "अभी आपकी पूछताछ भेजी नहीं जा सकी।",
    admin_status: "स्टेटस",
    admin_save: "अपडेट सेव करें",
    admin_delete: "डिलीट",
    admin_edit: "एडिट",
    admin_logout: "लॉगआउट",
  },
  gu: {
    brand: "ધોલેરા ઇન્ફ્રાસ્ટ્રક્ચર ઇન્ટેલિજન્સ",
    nav_home: "હોમ",
    nav_feed: "ગ્રોથ ટ્રેકર",
    nav_maps: "પ્રોજેક્ટ મેપ્સ",
    nav_growth: "ભવિષ્ય વૃદ્ધિ",
    nav_contact: "સંપર્ક",
    cta_whatsapp: "વોટ્સએપ કરો",
    cta_site_visit: "સાઇટ વિઝિટ માંગો",
    cta_brief: "પ્રોજેક્ટ બ્રીફ ડાઉનલોડ કરો",
    cta_price_sheet: "પ્રાઇસ શીટ માંગો",
    cta_map_request: "મેપ પેક માંગો",
    cta_consultation: "કન્સલ્ટેશન બુક કરો",
    latest_activity: "ઇન્ફ્રાસ્ટ્રક્ચર પ્રવૃત્તિ",
    feed_intro: "ઇન્ફ્રાસ્ટ્રક્ચર ઇન્ટેલિજન્સ મોનિટર",
    maps_heading: "મેપ્સ અને કનેક્ટિવિટી",
    growth_heading: "આ વિસ્તાર કેમ વિકસી રહ્યો છે",
    contact_heading: "રોકાણ ચર્ચા શરૂ કરો",
    lead_name: "પૂર્ણ નામ",
    lead_phone: "ફોન નંબર",
    lead_email: "ઇમેઇલ સરનામું",
    lead_message: "તમે શું જાણવા માંગો છો?",
    lead_visit_date: "પસંદગીની સાઇટ વિઝિટ તારીખ",
    lead_submit: "ઇન્ક્વાયરી મોકલો",
    admin_login: "એડમિન લોગિન",
    admin_updates: "અપડેટ્સ",
    admin_leads: "લીડ્સ",
    admin_dashboard: "ઓવરવ્યૂ",
    featured: "ફીચર્ડ",
    related_updates: "સંબંધિત અપડેટ્સ",
    back_to_feed: "ટ્રેકર પર પાછા જાઓ",
    read_more: "અપડેટ વાંચો",
    filters_search: "પ્રવૃત્તિ શોધો",
    filters_category: "કેટેગરી",
    filters_all: "બધી પ્રવૃત્તિઓ",
    no_updates: "હાલના ફિલ્ટર માટે કોઈ પ્રવૃત્તિ મળી નથી.",
    lead_success: "ઇન્ક્વાયરી મળી. અમારી ટીમ ટૂંક સમયમાં સંપર્ક કરશે.",
    lead_error: "હાલમાં તમારી ઇન્ક્વાયરી મોકલી શકાઈ નથી.",
    admin_status: "સ્ટેટસ",
    admin_save: "અપડેટ સેવ કરો",
    admin_delete: "ડિલીટ",
    admin_edit: "એડિટ",
    admin_logout: "લોગઆઉટ",
  },
};

